### ISSUE TITLE
Correccion de estilos

### ISSUE THREAD

**Issue by IaconoG** [MartinAMancilla/festival_rg#2]
**Estilo del elemento `<body>`: Ajustes en la imagen de fondo**
Estos cambios aseguran que la imagen de fondo se muestre correctamente, mejorando la apariencia visual del sitio.

- Añadir `background-repeat: no-repeat` para evitar que la imagen de fondo se repita.
- Añadir `background-size: cover` para que la imagen cubra todo el contenedor.

Nota: si todos los elementos `<body>` van a tener un mismo estilo, el estilado hacerlo una única vez en el archivos `style.css`. Lo unico que cambiaria es el `background-image: url( /* imagen para respectiva pagina */  );`

** Estructura del `<footer>` con estilos de bootstrap**
Footer utilizado para todas las paginas excepto el index

```html
<footer class="d-flex align-items-center py-3">
    <div class="row justify-content-between align-items-center">
      <div class="colums col-md-4 d-flex justify-content-center W">
        <img
          class="logof"
          src="/assets/membrete blanco.png"
          alt="Membrete Blanco"
        />
      </div>
      <div
        class="colums col-md-4 d-flex justify-content-center align-items-center text-center"
      >
        <p>
          SECRETARÍA DE COORDINACIÓN EJECUTIVA / DIRECCIÓN DE COMUNICACIÓN
          PÚBLICA
        </p>
      </div>
      <div class="colums col-md-4 d-flex justify-content-center">
        <img class="logof" src="/assets/G.png" alt="Logo G" />
      </div>
    </div>
  </footer>
```
```css
footer {
  position: sticky;
  /* bottom: 20px; kjjj */ 
  background-color:  #tu color / transparent; /* (otras paginas / index ) */
  min-height: 150px;
}
footer .row {
  margin: 0 auto;
  min-width: auto;
  width: 90vw;
}
footer .colums {
  min-width: 200px;
  width: auto;
  max-width: 1000px;
  margin: 0 auto;
}
footer p {
  /* Esto solo esta porque pusiste un margin-bottom en el p general y te afecta a todos lo p 🧑‍🦽‍➡️🧑‍🦽‍➡️🧑‍🦽‍➡️🧑‍🦽‍➡️🧑‍🦽‍➡️ */
 /* el `margin-bottom` lo aplica bootstrap 😶 */
  /* margin-bottom: 0; */
}
```
